name: Compilar PAK RE Engine
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar arquivos do repositorio
        uses: actions/checkout@v4.2.2

      - name: Descompactar pasta do mod
        run: |
          tar -xf natives.zip

      - name: Baixar RE-PAK Tool
        run: |
          curl -L -o repak.zip https://github.com
          powershell Expand-Archive -Path repak.zip -DestinationPath .

      - name: Criar o arquivo PAK do Mod
        shell: cmd
        run: |
          RE-Pak.exe pack natives re_chunk_000.pak.patch_001.pak

      - name: Disponibilizar para Download
        uses: actions/upload-artifact@v4
        with:
          name: mod-patch-ps4
          path: re_chunk_000.pak.patch_001.pak
